//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace GarageDoorPi.PiServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PiServer.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSensorStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<GarageDoorPi.PiServer.GetSensorStatusResponse> GetSensorStatusAsync(GarageDoorPi.PiServer.GetSensorStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckForPhone", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckForPhoneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<GarageDoorPi.PiServer.UpdateStatusResponse> UpdateStatusAsync(GarageDoorPi.PiServer.UpdateStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSensorStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSensorStatus", Namespace="http://tempuri.org/", Order=0)]
        public GarageDoorPi.PiServer.GetSensorStatusRequestBody Body;
        
        public GetSensorStatusRequest() {
        }
        
        public GetSensorStatusRequest(GarageDoorPi.PiServer.GetSensorStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSensorStatusRequestBody {
        
        public GetSensorStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSensorStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSensorStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public GarageDoorPi.PiServer.GetSensorStatusResponseBody Body;
        
        public GetSensorStatusResponse() {
        }
        
        public GetSensorStatusResponse(GarageDoorPi.PiServer.GetSensorStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSensorStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSensorStatusResult;
        
        public GetSensorStatusResponseBody() {
        }
        
        public GetSensorStatusResponseBody(string GetSensorStatusResult) {
            this.GetSensorStatusResult = GetSensorStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStatus", Namespace="http://tempuri.org/", Order=0)]
        public GarageDoorPi.PiServer.UpdateStatusRequestBody Body;
        
        public UpdateStatusRequest() {
        }
        
        public UpdateStatusRequest(GarageDoorPi.PiServer.UpdateStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sensor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string status;
        
        public UpdateStatusRequestBody() {
        }
        
        public UpdateStatusRequestBody(string sensor, string status) {
            this.sensor = sensor;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public GarageDoorPi.PiServer.UpdateStatusResponseBody Body;
        
        public UpdateStatusResponse() {
        }
        
        public UpdateStatusResponse(GarageDoorPi.PiServer.UpdateStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateStatusResult;
        
        public UpdateStatusResponseBody() {
        }
        
        public UpdateStatusResponseBody(bool UpdateStatusResult) {
            this.UpdateStatusResult = UpdateStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : GarageDoorPi.PiServer.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<GarageDoorPi.PiServer.ServiceSoap>, GarageDoorPi.PiServer.ServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient() : 
                base(ServiceSoapClient.GetDefaultBinding(), ServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.ServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GarageDoorPi.PiServer.GetSensorStatusResponse> GarageDoorPi.PiServer.ServiceSoap.GetSensorStatusAsync(GarageDoorPi.PiServer.GetSensorStatusRequest request) {
            return base.Channel.GetSensorStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<GarageDoorPi.PiServer.GetSensorStatusResponse> GetSensorStatusAsync() {
            GarageDoorPi.PiServer.GetSensorStatusRequest inValue = new GarageDoorPi.PiServer.GetSensorStatusRequest();
            inValue.Body = new GarageDoorPi.PiServer.GetSensorStatusRequestBody();
            return ((GarageDoorPi.PiServer.ServiceSoap)(this)).GetSensorStatusAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> CheckForPhoneAsync() {
            return base.Channel.CheckForPhoneAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GarageDoorPi.PiServer.UpdateStatusResponse> GarageDoorPi.PiServer.ServiceSoap.UpdateStatusAsync(GarageDoorPi.PiServer.UpdateStatusRequest request) {
            return base.Channel.UpdateStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<GarageDoorPi.PiServer.UpdateStatusResponse> UpdateStatusAsync(string sensor, string status) {
            GarageDoorPi.PiServer.UpdateStatusRequest inValue = new GarageDoorPi.PiServer.UpdateStatusRequest();
            inValue.Body = new GarageDoorPi.PiServer.UpdateStatusRequestBody();
            inValue.Body.sensor = sensor;
            inValue.Body.status = status;
            return ((GarageDoorPi.PiServer.ServiceSoap)(this)).UpdateStatusAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.118/PiServer/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.ServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ServiceSoapClient.GetEndpointAddress(EndpointConfiguration.ServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            ServiceSoap,
        }
    }
}
